In [7]:
set.seed(1)
X <- matrix(rpois(20, 1.5), nrow=4)
X

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    2    2    2   
[2,] 1    3    0    1    5   
[3,] 2    4    0    2    1   
[4,] 3    2    0    1    2

In [8]:
set.seed(1)
rpois(20,1.5)

[1] 1 1 2 3 0 3 4 2 2 0 0 0 2 1 2 1 2 5 1 2

In [6]:
rownames(X) <- rownames(X, do.NULL=FALSE, prefix="Trial.")
X

[,1] [,2] [,3] [,4] [,5]
Trial.1 1    0    2    2    2   
Trial.2 1    3    0    1    5   
Trial.3 2    4    0    2    1   
Trial.4 3    2    0    1    2

In [11]:
set.seed(1)
X <- matrix(rpois(20, 1.5), nrow=4)

In [12]:
rownames(X) <- rownames(X, prefix="Trial.")
X

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    2    2    2   
[2,] 1    3    0    1    5   
[3,] 2    4    0    2    1   
[4,] 3    2    0    1    2

In [7]:
set.seed(1)
X <- matrix(rpois(20, 1.5), nrow=4)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    2    2    2   
[2,] 1    3    0    1    5   
[3,] 2    4    0    2    1   
[4,] 3    2    0    1    2

In [10]:
rownames(X) <- rownames(X, do.NULL=FALSE)
X

[,1] [,2] [,3] [,4] [,5]
row1 1    0    2    2    2   
row2 1    3    0    1    5   
row3 2    4    0    2    1   
row4 3    2    0    1    2

In [13]:
dimnames(X) <- list(paste("row.", 1:4, sep=""), paste("drug.", 1:5, 
sep=""))
X

drug.1 drug.2 drug.3 drug.4 drug.5
row.1 1      0      2      2      2     
row.2 1      3      0      1      5     
row.3 2      4      0      2      1     
row.4 3      2      0      1      2

In [14]:
paste("row.", 1:4, sep="")

[1] "row.1" "row.2" "row.3" "row.4"

In [18]:
paste("row.",c(1,1,1,1))

[1] "row. 1" "row. 1" "row. 1" "row. 1"

In [19]:
paste("row.", 1:4)

[1] "row. 1" "row. 2" "row. 3" "row. 4"

In [20]:
list(paste("row.", 1:4, sep=""), paste("drug.", 1:5, 
sep=""))

[[1]]
[1] "row.1" "row.2" "row.3" "row.4"

[[2]]
[1] "drug.1" "drug.2" "drug.3" "drug.4" "drug.5"

In [1]:
set.seed(1)
X <- matrix(rpois(20, 1.5), nrow=4)

In [2]:
mean(X[,5])

[1] 2.5

In [3]:
var(X[4,])

[1] 1.3

In [4]:
rowSums(X)

[1]  7 10  9  8

In [5]:
colSums(X)

[1]  7  9  2  6 10

In [6]:
rowMeans(X)

[1] 1.4 2.0 1.8 1.6

In [7]:
colMeans(X)

[1] 1.75 2.25 0.50 1.50 2.50

In [8]:
apply(X,2,mean)

[1] 1.75 2.25 0.50 1.50 2.50

- 1행과 4행을 그룹 A, 2행과 3행을 그룹 B로 하여 그룹별로 계산하기 위해 group이라는 벡터 생성

In [9]:
group=c("A","B","B","A")

In [10]:
rowsum(X,group)

[,1] [,2] [,3] [,4] [,5]
A 4    2    2    3    4   
B 3    7    0    3    6

In [11]:
tapply(X, list(group[row(X)], col(X)), sum)

1 2 3 4 5
A 4 2 2 3 4
B 3 7 0 3 6

In [12]:
aggregate(X, list(group), sum)

Group.1 V1 V2 V3 V4 V5
1 A       4  2  2  3  4 
2 B       3  7  0  3  6

In [13]:
x <- seq(0, 50, 2); x
y <- c(1, 0.960235403, 0.844663774, 0.706936329, 0.7086414, 0.609795365, 0.513252644, 0.471399685, 0.384081274, 0.372277798, 0.334087432, 0.273307329, 0.25162333, 0.222786515, 0.210216526, 0.190591821, 0.166907195, 0.140731643, 0.12028785, 0.116460713, 0.092736872, 0.083972607, 0.088291404, 0.071790589, 0.059327414, 0.061706234)

[1]  0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
[26] 50

In [14]:
lm(log(y)~x)


Call:
lm(formula = log(y) ~ x)

Coefficients:
(Intercept)            x  
    0.04688     -0.05849  


In [15]:
a <- seq(0.01, 0.2, 0.005)

In [16]:
sumsq <- function(a, xv=x, yv=y) { 
  yf <- exp(-a*xv)
  sum((yv-yf)^2) 
}

In [17]:
a[min(sapply(a, sumsq)) == sapply(a, sumsq) ]

[1] 0.055

In [18]:
y <- c(8,3,5,7,6,6,8,9,2,3,9,4,10,4,11)


In [19]:
set.seed(1)
sample(y)

[1]  2  7  8  8  3 10  9  5  9  4  6  6 11  3  4

In [22]:
j=k=0
for (i in 1:5) {  
  j <- j+1
  k <- k+i*j
  print(i+j+k) 
}


[1] 3
[1] 9
[1] 20
[1] 38
[1] 65


In [23]:
cumprod(1:0)

[1] 1 0

In [25]:
cumprod(c(1,2,3,0))

[1] 1 2 6 0

In [26]:
gamma(1)

[1] 1

In [27]:
gamma(0)

Warning message in gamma(0):
“NaN이 생성되었습니다”


[1] NaN

In [28]:
gamma(2)

[1] 1

In [29]:
gamma(3)

[1] 2

In [30]:
gamma(4)

[1] 6

$\Gamma(x+1)=x!$

In [31]:
Area <- c(3.6, 5.1, 2.8, 2.4, 3.8, 3.1, 3.5, 2.1, 1.9, 1.5, 2.9, 3.3, 3.7, 1.8, 4.1, 3.9, 2.2, 4.4, 2.9, 0.8)

In [32]:
ifelse(Area>median(Area), "big", "small") 

[1] "big"   "big"   "small" "small" "big"   "big"   "big"   "small" "small"
[10] "small" "small" "big"   "big"   "small" "big"   "big"   "small" "big"  
[19] "small" "small"

In [33]:
log(0)

[1] -Inf

In [36]:
set.seed(1)
x <- runif(10000000) 

In [37]:
system.time(max(x))

 사용자  시스템 elapsed 
  0.014   0.004   0.018 

In [38]:
pc <- proc.time()  